### ISSUE TITLE
Installation of v0.3.0 failed under Linux due to missing ordered-namespace

### ISSUE THREAD

**Issue by stevesimmons** [Who8MyLunch/Jupyter_Video_Widget#2]
When I installed v0.3.0 via pip:

> pip install Jupyter-Video-Widget

the ordered-namespace package wasn't installed. I had to do a separate:

> pip install ordered-namespace

before installing the video widget.

The repo history here shows ordered-namespace was added to requirements.txt relatively recently. 
Perhaps this problem will be solved by cutting a new release for the Python Package Index.

**Comment by Who8MyLunch** [comment]
@stevesimmons thanks for letting me know.  I'll fix this when I get home this evening.

**Comment by Who8MyLunch** [comment]
New release uploaded with updated requirements in the setup.py file.
